# Catch Async

Utility used to wrap root async functions to avoid uncaught promise errors to go silent.

catchAsync is intented for use in the root-level of an asyncronous chain of
functions, basically avoiding the need of using `try/catch` and risking to leave silent errors in code.

# API Documentation

<!-- Generated by documentation.js. Update this documentation by updating the source code. -->

### Table of Contents

* [catchAsync](#catchasync)

## catchAsync

[src/index.js:36-49](https://github.com/Narzerus/catch-async/blob/ed3c3e5f988406e009cd1fb3ea42e29b4c8045d5/src/index.js#L36-L49 'Source code on GitHub')

Returns an async function wrapped in a try catch function. It
will by default log any error thrown in the async function unless
a handleError function is provided. In that case it will instead
call handleError

**Parameters**

* `asyncFunction` **any**
* `options` **[Object](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Object)?** (optional, default `{}`)
  * `options.handleError` **[Function](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Statements/function)?** if this function is provided
    then catchAsync will call it instead of logging the error
  * `options.logType`

Returns **[Function](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Statements/function)** wrapped async function
